### ISSUE TITLE
Add `hacktoberfest` label to the repo

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/evergreen#302]
Jenkins Evergreen participates in the Hacktoberfest: https://jenkins.io/blog/2018/10/01/hacktoberfest/

It would be great to add a hacktoberfest label to the repo so that it appears on https://hacktoberfest.digitalocean.com/

CC @batmat

**Comment by rtyler** [comment]
@oleg-nenashev Do you mean "topic"? on the repo home page?

**Comment by batmat** [comment]
Yes. Like jenkins.io repo for instance.

Le jeu. 4 oct. 2018 à 16:10, R. Tyler Croy <notifications@github.com> a
écrit :
